services:
  - type: web
    name: cupuri-backend
    runtime: node
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3009
